// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: candidates.sql

package repositories

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const candidateAndJobRoles = `-- name: CandidateAndJobRoles :many
select c.id, c.full_name, c.email, c.phone, c.file_id, c.status, c.created_at, c.updated_at, jr.id, jr.title, jr.department_id, jr.level, jr.salary_range, jr.location, jr.is_active, jr.created_at, jr.updated_at, a.applied_at
from candidates c
join applications a on c.id = a.candidate_id
join job_roles jr on a.job_role_id = jr.id
where jr.is_active = true
and (c.full_name ilike '%' || $1 || '%' or $1 is null)
order by case when c.full_name = $1 then 0 else 1 end, c.full_name asc
limit $3 offset $2
`

type CandidateAndJobRolesParams struct {
	NameSearch sql.NullString `json:"name_search"`
	Pagequery  int32          `json:"pagequery"`
	Limitquery int32          `json:"limitquery"`
}

type CandidateAndJobRolesRow struct {
	Candidate Candidate `json:"candidate"`
	JobRole   JobRole   `json:"job_role"`
	AppliedAt time.Time `json:"applied_at"`
}

func (q *Queries) CandidateAndJobRoles(ctx context.Context, arg CandidateAndJobRolesParams) ([]CandidateAndJobRolesRow, error) {
	rows, err := q.db.Query(ctx, candidateAndJobRoles, arg.NameSearch, arg.Pagequery, arg.Limitquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CandidateAndJobRolesRow{}
	for rows.Next() {
		var i CandidateAndJobRolesRow
		if err := rows.Scan(
			&i.Candidate.ID,
			&i.Candidate.FullName,
			&i.Candidate.Email,
			&i.Candidate.Phone,
			&i.Candidate.FileID,
			&i.Candidate.Status,
			&i.Candidate.CreatedAt,
			&i.Candidate.UpdatedAt,
			&i.JobRole.ID,
			&i.JobRole.Title,
			&i.JobRole.DepartmentID,
			&i.JobRole.Level,
			&i.JobRole.SalaryRange,
			&i.JobRole.Location,
			&i.JobRole.IsActive,
			&i.JobRole.CreatedAt,
			&i.JobRole.UpdatedAt,
			&i.AppliedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCandidate = `-- name: CreateCandidate :one
INSERT INTO candidates (
    id, full_name, email, phone, file_id, status
) VALUES (
    uuid_generate_v4(), $1, $2, $3, $4, $5
)
RETURNING id, full_name, email, phone, file_id, status, created_at, updated_at
`

type CreateCandidateParams struct {
	FullName string    `json:"full_name"`
	Email    string    `json:"email"`
	Phone    string    `json:"phone"`
	FileID   uuid.UUID `json:"file_id"`
	Status   string    `json:"status"`
}

func (q *Queries) CreateCandidate(ctx context.Context, arg CreateCandidateParams) (Candidate, error) {
	row := q.db.QueryRow(ctx, createCandidate,
		arg.FullName,
		arg.Email,
		arg.Phone,
		arg.FileID,
		arg.Status,
	)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.FileID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCandidate = `-- name: DeleteCandidate :exec
delete from candidates
where id = $1
`

func (q *Queries) DeleteCandidate(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCandidate, id)
	return err
}

const getCandidate = `-- name: GetCandidate :one
select id, full_name, email, phone, file_id, status, created_at, updated_at
from candidates
where id = $1
limit 1
`

func (q *Queries) GetCandidate(ctx context.Context, id uuid.UUID) (Candidate, error) {
	row := q.db.QueryRow(ctx, getCandidate, id)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.FileID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCandidates = `-- name: ListCandidates :many
select id, full_name, email, phone, file_id, status, created_at, updated_at
from candidates
order by created_at desc
`

func (q *Queries) ListCandidates(ctx context.Context) ([]Candidate, error) {
	rows, err := q.db.Query(ctx, listCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Candidate{}
	for rows.Next() {
		var i Candidate
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.Phone,
			&i.FileID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCandidate = `-- name: UpdateCandidate :exec
UPDATE candidates
SET full_name = $2,
    email = $3,
    phone = $4,
    file_id = $5,
    status = $6
WHERE id = $1
`

type UpdateCandidateParams struct {
	ID       uuid.UUID `json:"id"`
	FullName string    `json:"full_name"`
	Email    string    `json:"email"`
	Phone    string    `json:"phone"`
	FileID   uuid.UUID `json:"file_id"`
	Status   string    `json:"status"`
}

func (q *Queries) UpdateCandidate(ctx context.Context, arg UpdateCandidateParams) error {
	_, err := q.db.Exec(ctx, updateCandidate,
		arg.ID,
		arg.FullName,
		arg.Email,
		arg.Phone,
		arg.FileID,
		arg.Status,
	)
	return err
}
