// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: screen_resume.proto

package repositories

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ResumeScreener_ScreenResume_FullMethodName = "/repositories.ResumeScreener/ScreenResume"
)

// ResumeScreenerClient is the client API for ResumeScreener service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResumeScreenerClient interface {
	ScreenResume(ctx context.Context, in *ScreenResumeRequest, opts ...grpc.CallOption) (*ScreenResumeResponse, error)
}

type resumeScreenerClient struct {
	cc grpc.ClientConnInterface
}

func NewResumeScreenerClient(cc grpc.ClientConnInterface) ResumeScreenerClient {
	return &resumeScreenerClient{cc}
}

func (c *resumeScreenerClient) ScreenResume(ctx context.Context, in *ScreenResumeRequest, opts ...grpc.CallOption) (*ScreenResumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScreenResumeResponse)
	err := c.cc.Invoke(ctx, ResumeScreener_ScreenResume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResumeScreenerServer is the server API for ResumeScreener service.
// All implementations must embed UnimplementedResumeScreenerServer
// for forward compatibility.
type ResumeScreenerServer interface {
	ScreenResume(context.Context, *ScreenResumeRequest) (*ScreenResumeResponse, error)
	mustEmbedUnimplementedResumeScreenerServer()
}

// UnimplementedResumeScreenerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResumeScreenerServer struct{}

func (UnimplementedResumeScreenerServer) ScreenResume(context.Context, *ScreenResumeRequest) (*ScreenResumeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScreenResume not implemented")
}
func (UnimplementedResumeScreenerServer) mustEmbedUnimplementedResumeScreenerServer() {}
func (UnimplementedResumeScreenerServer) testEmbeddedByValue()                        {}

// UnsafeResumeScreenerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResumeScreenerServer will
// result in compilation errors.
type UnsafeResumeScreenerServer interface {
	mustEmbedUnimplementedResumeScreenerServer()
}

func RegisterResumeScreenerServer(s grpc.ServiceRegistrar, srv ResumeScreenerServer) {
	// If the following call pancis, it indicates UnimplementedResumeScreenerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ResumeScreener_ServiceDesc, srv)
}

func _ResumeScreener_ScreenResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScreenResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResumeScreenerServer).ScreenResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResumeScreener_ScreenResume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResumeScreenerServer).ScreenResume(ctx, req.(*ScreenResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ResumeScreener_ServiceDesc is the grpc.ServiceDesc for ResumeScreener service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResumeScreener_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "repositories.ResumeScreener",
	HandlerType: (*ResumeScreenerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScreenResume",
			Handler:    _ResumeScreener_ScreenResume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "screen_resume.proto",
}
